// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/types";
import type * as prismicClient from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *footermenu → linkgroup*
 */
export interface FootermenuDocumentDataLinkgroupItem {
	/**
	 * label field in *footermenu → linkgroup*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footermenu.linkgroup[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * link field in *footermenu → linkgroup*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footermenu.linkgroup[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Item in *footermenu → socialmediagroup*
 */
export interface FootermenuDocumentDataSocialmediagroupItem {
	/**
	 * image field in *footermenu → socialmediagroup*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footermenu.socialmediagroup[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * imagelink field in *footermenu → socialmediagroup*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footermenu.socialmediagroup[].imagelink
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	imagelink: prismic.LinkField;
}

/**
 * Content for footermenu documents
 */
interface FootermenuDocumentData {
	/**
	 * logo field in *footermenu*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footermenu.logo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	logo: prismic.ImageField<never>;
	
	/**
	 * description field in *footermenu*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footermenu.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
	
	/**
	 * textrights field in *footermenu*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footermenu.textrights
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	textrights: prismic.RichTextField;
	
	/**
	 * linkgroup field in *footermenu*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footermenu.linkgroup[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	linkgroup: prismic.GroupField<Simplify<FootermenuDocumentDataLinkgroupItem>>;
	
	/**
	 * socialmediagroup field in *footermenu*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footermenu.socialmediagroup[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	socialmediagroup: prismic.GroupField<Simplify<FootermenuDocumentDataSocialmediagroupItem>>;
}

/**
 * footermenu document from Prismic
 *
 * - **API ID**: `footermenu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FootermenuDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<FootermenuDocumentData>, "footermenu", Lang>;

type HomepageDocumentDataSlicesSlice = HeroSlice | IdeasSlice | CardListSlice | LogoListSlice | MetricsSlice | ServicesSlice | ProjectsSlice | ClientsSlice | StaffSlice | ContactSlice

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
	/**
	 * seotitle field in *homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.seotitle
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	seotitle: prismic.KeyTextField;
	
	/**
	 * seodescription field in *homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.seodescription
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	seodescription: prismic.KeyTextField;
	
	/**
	 * Slice Zone field in *homepage*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<HomepageDocumentData>, "homepage", Lang>;

/**
 * Item in *landingFooter → contactgroup*
 */
export interface LandingfooterDocumentDataContactgroupItem {
	/**
	 * icon field in *landingFooter → contactgroup*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingfooter.contactgroup[].icon
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	icon: prismic.ImageField<never>;
	
	/**
	 * label field in *landingFooter → contactgroup*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingfooter.contactgroup[].label
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	label: prismic.RichTextField;
	
	/**
	 * url field in *landingFooter → contactgroup*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingfooter.contactgroup[].url
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	url: prismic.LinkField;
}

/**
 * Item in *landingFooter → navLinks*
 */
export interface LandingfooterDocumentDataNavlinksItem {
	/**
	 * nav field in *landingFooter → navLinks*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingfooter.navlinks[].nav
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	nav: prismic.RichTextField;
	
	/**
	 * link field in *landingFooter → navLinks*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingfooter.navlinks[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Content for landingFooter documents
 */
interface LandingfooterDocumentData {
	/**
	 * logo field in *landingFooter*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingfooter.logo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	logo: prismic.ImageField<never>;
	
	/**
	 * description field in *landingFooter*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingfooter.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
	
	/**
	 * copyright field in *landingFooter*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingfooter.copyright
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	copyright: prismic.RichTextField;
	
	/**
	 * contactgroup field in *landingFooter*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingfooter.contactgroup[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	contactgroup: prismic.GroupField<Simplify<LandingfooterDocumentDataContactgroupItem>>;
	
	/**
	 * navLinks field in *landingFooter*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingfooter.navlinks[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	navlinks: prismic.GroupField<Simplify<LandingfooterDocumentDataNavlinksItem>>;
}

/**
 * landingFooter document from Prismic
 *
 * - **API ID**: `landingfooter`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingfooterDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<LandingfooterDocumentData>, "landingfooter", Lang>;

/**
 * Item in *LandingNav → navLink*
 */
export interface LandingnavDocumentDataNavlinkItem {
	/**
	 * text field in *LandingNav → navLink*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingnav.navlink[].text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	text: prismic.KeyTextField;
	
	/**
	 * url field in *LandingNav → navLink*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingnav.navlink[].url
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	url: prismic.LinkField;
}

/**
 * Content for LandingNav documents
 */
interface LandingnavDocumentData {
	/**
	 * logo field in *LandingNav*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingnav.logo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	logo: prismic.ImageField<never>;
	
	/**
	 * logoUrl field in *LandingNav*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingnav.logourl
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	logourl: prismic.LinkField;
	
	/**
	 * navLink field in *LandingNav*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingnav.navlink[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	navlink: prismic.GroupField<Simplify<LandingnavDocumentDataNavlinkItem>>;
	
	/**
	 * callBtn field in *LandingNav*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingnav.callbtn
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	callbtn: prismic.KeyTextField;
	
	/**
	 * callBtnLink field in *LandingNav*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingnav.callbtnlink
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	callbtnlink: prismic.LinkField;
}

/**
 * LandingNav document from Prismic
 *
 * - **API ID**: `landingnav`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingnavDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<LandingnavDocumentData>, "landingnav", Lang>;

type LandingpageDocumentDataSlicesSlice = LandingCustomerReviewSlice | LandingFaqSlice | LandingHeroSlice | LandingTimelineSlice | AboutSlice | LandingServicesSlice | OurProjectsSlice | SliceBenefitsSlice | LandingSubheroSlice | LandingBenefitsTopSlice | LandingClosingFormSlice | LandingVideoShowcaseSlice

/**
 * Content for LandingPage documents
 */
interface LandingpageDocumentData {
	/**
	 * seoTitle field in *LandingPage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingpage.seotitle
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	seotitle: prismic.KeyTextField;
	
	/**
	 * seoDescription field in *LandingPage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingpage.seodescription
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	seodescription: prismic.KeyTextField;
	
	/**
	 * Slice Zone field in *LandingPage*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingpage.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<LandingpageDocumentDataSlicesSlice>;
}

/**
 * LandingPage document from Prismic
 *
 * - **API ID**: `landingpage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingpageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<LandingpageDocumentData>, "landingpage", Lang>;

/**
 * Item in *menuTop → menuLinks*
 */
export interface MenutopDocumentDataMenulinksItem {
	/**
	 * label field in *menuTop → menuLinks*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menutop.menulinks[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * link field in *menuTop → menuLinks*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menutop.menulinks[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Content for menuTop documents
 */
interface MenutopDocumentData {
	/**
	 * logo field in *menuTop*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menutop.logo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	logo: prismic.ImageField<never>;
	
	/**
	 * title field in *menuTop*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menutop.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;
	
	/**
	 * callToActionText field in *menuTop*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menutop.calltoactiontext
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	calltoactiontext: prismic.RichTextField;
	
	/**
	 * callToActionURL field in *menuTop*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menutop.calltoactionurl
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	calltoactionurl: prismic.LinkField;
	
	/**
	 * menuLinks field in *menuTop*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menutop.menulinks[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	menulinks: prismic.GroupField<Simplify<MenutopDocumentDataMenulinksItem>>;
}

/**
 * menuTop document from Prismic
 *
 * - **API ID**: `menutop`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenutopDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<MenutopDocumentData>, "menutop", Lang>;

type PageDocumentDataSlicesSlice = HeroSlice | IdeasSlice | CardListSlice | LogoListSlice | MetricsSlice | ServicesSlice | ProjectsSlice | ClientsSlice | StaffSlice | ContactSlice

/**
 * Content for page documents
 */
interface PageDocumentData {
	/**
	 * seotitle field in *page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.seotitle
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	seotitle: prismic.KeyTextField;
	
	/**
	 * seodescription field in *page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.seodescription
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	seodescription: prismic.KeyTextField;
	
	/**
	 * Slice Zone field in *page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

/**
 * page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = FootermenuDocument | HomepageDocument | LandingfooterDocument | LandingnavDocument | LandingpageDocument | MenutopDocument | PageDocument;

/**
 * Primary content in *CardList → Default → Primary*
 */
export interface CardListSliceDefaultPrimary {
	/**
	 * title field in *CardList → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: card_list.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;
	
	/**
	 * description field in *CardList → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: card_list.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
}

/**
 * Primary content in *CardList → Items*
 */
export interface CardListSliceDefaultItem {
	/**
	 * cardTitle field in *CardList → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: card_list.items[].cardTitle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	cardTitle: prismic.RichTextField;
	
	/**
	 * cardDescription field in *CardList → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: card_list.items[].cardDescription
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	cardDescription: prismic.RichTextField;
	
	/**
	 * cardImage field in *CardList → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: card_list.items[].cardImage
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	cardImage: prismic.ImageField<never>;
}

/**
 * Default variation for CardList Slice
 *
 * - **API ID**: `default`
 * - **Description**: CardList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardListSliceDefault = prismic.SharedSliceVariation<"default", Simplify<CardListSliceDefaultPrimary>, Simplify<CardListSliceDefaultItem>>;

/**
 * Slice variation for *CardList*
 */
type CardListSliceVariation = CardListSliceDefault

/**
 * CardList Shared Slice
 *
 * - **API ID**: `card_list`
 * - **Description**: CardList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardListSlice = prismic.SharedSlice<"card_list", CardListSliceVariation>;

/**
 * Primary content in *Comparative → Default → Primary*
 */
export interface ClientsSliceDefaultPrimary {
	/**
	 * title field in *Comparative → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * description field in *Comparative → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;
}

/**
 * Primary content in *Comparative → Items*
 */
export interface ClientsSliceDefaultItem {
	/**
	 * title field in *Comparative → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;
	
	/**
	 * description field in *Comparative → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;
	
	/**
	 * ico1 field in *Comparative → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].ico
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	ico: prismic.ImageField<never>;
	
	/**
	 * description1 field in *Comparative → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].description1
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description1: prismic.KeyTextField;
	
	/**
	 * ico2 field in *Comparative → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].ico2
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	ico2: prismic.ImageField<never>;
	
	/**
	 * description2 field in *Comparative → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].description2
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description2: prismic.KeyTextField;
	
	/**
	 * ico3 field in *Comparative → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].ico3
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	ico3: prismic.ImageField<never>;
	
	/**
	 * description3 field in *Comparative → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].description3
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description3: prismic.KeyTextField;
	
	/**
	 * ico4 field in *Comparative → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].ico4
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	ico4: prismic.ImageField<never>;
	
	/**
	 * description4 field in *Comparative → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].description4
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description4: prismic.KeyTextField;
	
	/**
	 * ico5 field in *Comparative → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].ico5
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	ico5: prismic.ImageField<never>;
	
	/**
	 * description5 field in *Comparative → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].description5
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description5: prismic.KeyTextField;
	
	/**
	 * buttontext field in *Comparative → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].buttontext
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	buttontext: prismic.KeyTextField;
	
	/**
	 * buttonlink field in *Comparative → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].buttonlink
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	buttonlink: prismic.LinkField;
}

/**
 * Default variation for Comparative Slice
 *
 * - **API ID**: `default`
 * - **Description**: Clients
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ClientsSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ClientsSliceDefaultPrimary>, Simplify<ClientsSliceDefaultItem>>;

/**
 * Slice variation for *Comparative*
 */
type ClientsSliceVariation = ClientsSliceDefault

/**
 * Comparative Shared Slice
 *
 * - **API ID**: `clients`
 * - **Description**: Clients
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ClientsSlice = prismic.SharedSlice<"clients", ClientsSliceVariation>;

/**
 * Primary content in *Contact → Default → Primary*
 */
export interface ContactSliceDefaultPrimary {
	/**
	 * title field in *Contact → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;
	
	/**
	 * subtitle field in *Contact → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subtitle: prismic.RichTextField;
	
	/**
	 * name field in *Contact → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * email field in *Contact → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.email
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	email: prismic.KeyTextField;
	
	/**
	 * message field in *Contact → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.message
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	message: prismic.KeyTextField;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ContactSliceDefaultPrimary>, never>;

/**
 * Primary content in *Contact → cotizarForm → Primary*
 */
export interface ContactSliceCotizarFormPrimary {
	/**
	 * subtitle field in *Contact → cotizarForm → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.cotizarForm.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subtitle: prismic.RichTextField;
	
	/**
	 * name field in *Contact → cotizarForm → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.cotizarForm.primary.name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * email field in *Contact → cotizarForm → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.cotizarForm.primary.email
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	email: prismic.KeyTextField;
}

/**
 * cotizarForm variation for Contact Slice
 *
 * - **API ID**: `cotizarForm`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceCotizarForm = prismic.SharedSliceVariation<"cotizarForm", Simplify<ContactSliceCotizarFormPrimary>, never>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault | ContactSliceCotizarForm

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSlice = prismic.SharedSlice<"contact", ContactSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * invertedLayout field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: hero.default.primary.invertedlayout
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	invertedlayout: prismic.BooleanField;
	
	/**
	 * image field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * description field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
	
	/**
	 * buttonText field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.buttontext
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	buttontext: prismic.KeyTextField;
	
	/**
	 * buttonLink field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.buttonlink
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	buttonlink: prismic.LinkField;
	
	/**
	 * mobileImage field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.mobileimage
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	mobileimage: prismic.ImageField<never>;
	
	/**
	 * title field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<"default", Simplify<HeroSliceDefaultPrimary>, never>;

/**
 * Primary content in *Hero → noButtonNoDescription → Primary*
 */
export interface HeroSliceNoButtonNoDescriptionPrimary {
	/**
	 * invertedLayout field in *Hero → noButtonNoDescription → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: hero.noButtonNoDescription.primary.invertedlayout
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	invertedlayout: prismic.BooleanField;
	
	/**
	 * image field in *Hero → noButtonNoDescription → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.noButtonNoDescription.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * title field in *Hero → noButtonNoDescription → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.noButtonNoDescription.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;
	
	/**
	 * mobileImage field in *Hero → noButtonNoDescription → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.noButtonNoDescription.primary.mobileimage
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	mobileimage: prismic.ImageField<never>;
}

/**
 * noButtonNoDescription variation for Hero Slice
 *
 * - **API ID**: `noButtonNoDescription`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceNoButtonNoDescription = prismic.SharedSliceVariation<"noButtonNoDescription", Simplify<HeroSliceNoButtonNoDescriptionPrimary>, never>;

/**
 * Primary content in *Hero → noButton → Primary*
 */
export interface HeroSliceNoButtonPrimary {
	/**
	 * invertedLayout field in *Hero → noButton → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: hero.noButton.primary.invertedlayout
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	invertedlayout: prismic.BooleanField;
	
	/**
	 * image field in *Hero → noButton → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.noButton.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * title field in *Hero → noButton → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.noButton.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;
	
	/**
	 * description field in *Hero → noButton → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.noButton.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
	
	/**
	 * mobileImage field in *Hero → noButton → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.noButton.primary.mobileimage
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	mobileimage: prismic.ImageField<never>;
}

/**
 * noButton variation for Hero Slice
 *
 * - **API ID**: `noButton`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceNoButton = prismic.SharedSliceVariation<"noButton", Simplify<HeroSliceNoButtonPrimary>, never>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceNoButtonNoDescription | HeroSliceNoButton

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Ideas → Default → Primary*
 */
export interface IdeasSliceDefaultPrimary {
	/**
	 * subtittle field in *Ideas → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.default.primary.subtittle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subtittle: prismic.RichTextField;
	
	/**
	 * tittle field in *Ideas → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.default.primary.tittle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	tittle: prismic.RichTextField;
	
	/**
	 * buttonText field in *Ideas → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.default.primary.buttontext
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	buttontext: prismic.KeyTextField;
	
	/**
	 * buttonLink field in *Ideas → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.default.primary.buttonlink
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	buttonlink: prismic.LinkField;
	
	/**
	 * bgColorInitial field in *Ideas → Default → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.default.primary.bgcolorInitial
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	bgcolorInitial: prismic.ColorField;
	
	/**
	 * bgColorEnd field in *Ideas → Default → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.default.primary.bgcolorend
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	bgcolorend: prismic.ColorField;
}

/**
 * Default variation for Ideas Slice
 *
 * - **API ID**: `default`
 * - **Description**: Ideas
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IdeasSliceDefault = prismic.SharedSliceVariation<"default", Simplify<IdeasSliceDefaultPrimary>, never>;

/**
 * Primary content in *Ideas → noButtonNobg → Primary*
 */
export interface IdeasSliceNoButtonNobgPrimary {
	/**
	 * subtittle field in *Ideas → noButtonNobg → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.noButtonNobg.primary.subtittle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subtittle: prismic.RichTextField;
	
	/**
	 * tittle field in *Ideas → noButtonNobg → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.noButtonNobg.primary.tittle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	tittle: prismic.RichTextField;
}

/**
 * noButtonNobg variation for Ideas Slice
 *
 * - **API ID**: `noButtonNobg`
 * - **Description**: Ideas
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IdeasSliceNoButtonNobg = prismic.SharedSliceVariation<"noButtonNobg", Simplify<IdeasSliceNoButtonNobgPrimary>, never>;

/**
 * Primary content in *Ideas → noButton → Primary*
 */
export interface IdeasSliceNoButtonPrimary {
	/**
	 * subtittle field in *Ideas → noButton → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.noButton.primary.subtittle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subtittle: prismic.RichTextField;
	
	/**
	 * tittle field in *Ideas → noButton → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.noButton.primary.tittle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	tittle: prismic.RichTextField;
	
	/**
	 * bgColorInitial field in *Ideas → noButton → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.noButton.primary.bgcolorInitial
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	bgcolorInitial: prismic.ColorField;
	
	/**
	 * bgColorEnd field in *Ideas → noButton → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.noButton.primary.bgcolorend
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	bgcolorend: prismic.ColorField;
}

/**
 * noButton variation for Ideas Slice
 *
 * - **API ID**: `noButton`
 * - **Description**: Ideas
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IdeasSliceNoButton = prismic.SharedSliceVariation<"noButton", Simplify<IdeasSliceNoButtonPrimary>, never>;

/**
 * Slice variation for *Ideas*
 */
type IdeasSliceVariation = IdeasSliceDefault | IdeasSliceNoButtonNobg | IdeasSliceNoButton

/**
 * Ideas Shared Slice
 *
 * - **API ID**: `ideas`
 * - **Description**: Ideas
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IdeasSlice = prismic.SharedSlice<"ideas", IdeasSliceVariation>;

/**
 * Primary content in *LandingAbout → Default → Primary*
 */
export interface AboutSliceDefaultPrimary {
	/**
	 * Title field in *LandingAbout → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: This is where it all begins...
	 * - **API ID Path**: about.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * Description field in *LandingAbout → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: A nice description of your feature
	 * - **API ID Path**: about.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
	
	/**
	 * image field in *LandingAbout → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Default variation for LandingAbout Slice
 *
 * - **API ID**: `default`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<"default", Simplify<AboutSliceDefaultPrimary>, never>;

/**
 * Slice variation for *LandingAbout*
 */
type AboutSliceVariation = AboutSliceDefault

/**
 * LandingAbout Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSlice = prismic.SharedSlice<"about", AboutSliceVariation>;

/**
 * Primary content in *LandingBenefits → Default → Primary*
 */
export interface SliceBenefitsSliceDefaultPrimary {
	/**
	 * Title field in *LandingBenefits → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: This is where it all begins...
	 * - **API ID Path**: slice_benefits.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
}

/**
 * Primary content in *LandingBenefits → Items*
 */
export interface SliceBenefitsSliceDefaultItem {
	/**
	 * icon field in *LandingBenefits → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: slice_benefits.items[].icon
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	icon: prismic.ImageField<never>;
	
	/**
	 * keyTitle field in *LandingBenefits → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: slice_benefits.items[].keytitle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	keytitle: prismic.RichTextField;
	
	/**
	 * description field in *LandingBenefits → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: slice_benefits.items[].description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
}

/**
 * Default variation for LandingBenefits Slice
 *
 * - **API ID**: `default`
 * - **Description**: SliceBenefits
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliceBenefitsSliceDefault = prismic.SharedSliceVariation<"default", Simplify<SliceBenefitsSliceDefaultPrimary>, Simplify<SliceBenefitsSliceDefaultItem>>;

/**
 * Slice variation for *LandingBenefits*
 */
type SliceBenefitsSliceVariation = SliceBenefitsSliceDefault

/**
 * LandingBenefits Shared Slice
 *
 * - **API ID**: `slice_benefits`
 * - **Description**: SliceBenefits
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliceBenefitsSlice = prismic.SharedSlice<"slice_benefits", SliceBenefitsSliceVariation>;

/**
 * Primary content in *LandingBenefitsTop → Default → Primary*
 */
export interface LandingBenefitsTopSliceDefaultPrimary {
	/**
	 * bgImage field in *LandingBenefitsTop → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_benefits_top.default.primary.bgimage
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	bgimage: prismic.ImageField<never>;
}

/**
 * Primary content in *LandingBenefitsTop → Items*
 */
export interface LandingBenefitsTopSliceDefaultItem {
	/**
	 * metric field in *LandingBenefitsTop → Items*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_benefits_top.items[].metric
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	metric: prismic.TitleField;
	
	/**
	 * metricText field in *LandingBenefitsTop → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_benefits_top.items[].metrictext
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	metrictext: prismic.RichTextField;
}

/**
 * Default variation for LandingBenefitsTop Slice
 *
 * - **API ID**: `default`
 * - **Description**: LandingBenefitsTop
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingBenefitsTopSliceDefault = prismic.SharedSliceVariation<"default", Simplify<LandingBenefitsTopSliceDefaultPrimary>, Simplify<LandingBenefitsTopSliceDefaultItem>>;

/**
 * Slice variation for *LandingBenefitsTop*
 */
type LandingBenefitsTopSliceVariation = LandingBenefitsTopSliceDefault

/**
 * LandingBenefitsTop Shared Slice
 *
 * - **API ID**: `landing_benefits_top`
 * - **Description**: LandingBenefitsTop
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingBenefitsTopSlice = prismic.SharedSlice<"landing_benefits_top", LandingBenefitsTopSliceVariation>;

/**
 * Primary content in *LandingClosingForm → Default → Primary*
 */
export interface LandingClosingFormSliceDefaultPrimary {
	/**
	 * Title field in *LandingClosingForm → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: This is where it all begins...
	 * - **API ID Path**: landing_closing_form.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * Description field in *LandingClosingForm → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: A nice description of your feature
	 * - **API ID Path**: landing_closing_form.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
	
	/**
	 * ctaText field in *LandingClosingForm → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_closing_form.default.primary.ctatext
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	ctatext: prismic.RichTextField;
	
	/**
	 * bgImage field in *LandingClosingForm → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_closing_form.default.primary.bgimage
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	bgimage: prismic.ImageField<never>;
}

/**
 * Default variation for LandingClosingForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: LandingClosingForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingClosingFormSliceDefault = prismic.SharedSliceVariation<"default", Simplify<LandingClosingFormSliceDefaultPrimary>, never>;

/**
 * Slice variation for *LandingClosingForm*
 */
type LandingClosingFormSliceVariation = LandingClosingFormSliceDefault

/**
 * LandingClosingForm Shared Slice
 *
 * - **API ID**: `landing_closing_form`
 * - **Description**: LandingClosingForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingClosingFormSlice = prismic.SharedSlice<"landing_closing_form", LandingClosingFormSliceVariation>;

/**
 * Primary content in *LandingCustomerReview → Default → Primary*
 */
export interface LandingCustomerReviewSliceDefaultPrimary {
	/**
	 * Title field in *LandingCustomerReview → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: This is where it all begins...
	 * - **API ID Path**: landing_customer_review.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
}

/**
 * Primary content in *LandingCustomerReview → Items*
 */
export interface LandingCustomerReviewSliceDefaultItem {
	/**
	 * userIcon field in *LandingCustomerReview → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_customer_review.items[].usericon
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	usericon: prismic.ImageField<never>;
	
	/**
	 * userName field in *LandingCustomerReview → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_customer_review.items[].username
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	username: prismic.RichTextField;
	
	/**
	 * userReview field in *LandingCustomerReview → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_customer_review.items[].userreview
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	userreview: prismic.RichTextField;
	
	/**
	 * stars field in *LandingCustomerReview → Items*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_customer_review.items[].stars
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	stars: prismic.NumberField;
	
	/**
	 * googleLink field in *LandingCustomerReview → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_customer_review.items[].googlelink
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	googlelink: prismic.LinkField;
}

/**
 * Default variation for LandingCustomerReview Slice
 *
 * - **API ID**: `default`
 * - **Description**: LandingCustomerReview
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingCustomerReviewSliceDefault = prismic.SharedSliceVariation<"default", Simplify<LandingCustomerReviewSliceDefaultPrimary>, Simplify<LandingCustomerReviewSliceDefaultItem>>;

/**
 * Slice variation for *LandingCustomerReview*
 */
type LandingCustomerReviewSliceVariation = LandingCustomerReviewSliceDefault

/**
 * LandingCustomerReview Shared Slice
 *
 * - **API ID**: `landing_customer_review`
 * - **Description**: LandingCustomerReview
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingCustomerReviewSlice = prismic.SharedSlice<"landing_customer_review", LandingCustomerReviewSliceVariation>;

/**
 * Primary content in *LandingFaq → Default → Primary*
 */
export interface LandingFaqSliceDefaultPrimary {
	/**
	 * Title field in *LandingFaq → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: This is where it all begins...
	 * - **API ID Path**: landing_faq.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
}

/**
 * Primary content in *LandingFaq → Items*
 */
export interface LandingFaqSliceDefaultItem {
	/**
	 * question field in *LandingFaq → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_faq.items[].question
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	question: prismic.RichTextField;
	
	/**
	 * answer field in *LandingFaq → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_faq.items[].answer
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	answer: prismic.RichTextField;
}

/**
 * Default variation for LandingFaq Slice
 *
 * - **API ID**: `default`
 * - **Description**: LandingFaq
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingFaqSliceDefault = prismic.SharedSliceVariation<"default", Simplify<LandingFaqSliceDefaultPrimary>, Simplify<LandingFaqSliceDefaultItem>>;

/**
 * Slice variation for *LandingFaq*
 */
type LandingFaqSliceVariation = LandingFaqSliceDefault

/**
 * LandingFaq Shared Slice
 *
 * - **API ID**: `landing_faq`
 * - **Description**: LandingFaq
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingFaqSlice = prismic.SharedSlice<"landing_faq", LandingFaqSliceVariation>;

/**
 * Primary content in *LandingHero → Default → Primary*
 */
export interface LandingHeroSliceDefaultPrimary {
	/**
	 * Title field in *LandingHero → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: This is where it all begins...
	 * - **API ID Path**: landing_hero.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * subtitle field in *LandingHero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_hero.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subtitle: prismic.RichTextField;
	
	/**
	 * tagline field in *LandingHero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_hero.default.primary.tagline
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	tagline: prismic.RichTextField;
	
	/**
	 * formTitle field in *LandingHero → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_hero.default.primary.formtitle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	formtitle: prismic.TitleField;
	
	/**
	 * formSubtitle field in *LandingHero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_hero.default.primary.formsubtitle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	formsubtitle: prismic.RichTextField;
	
	/**
	 * ctaText field in *LandingHero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_hero.default.primary.ctatext
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	ctatext: prismic.RichTextField;
	
	/**
	 * bgImage field in *LandingHero → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_hero.default.primary.bgimage
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	bgimage: prismic.ImageField<never>;
}

/**
 * Primary content in *LandingHero → Items*
 */
export interface LandingHeroSliceDefaultItem {
	/**
	 * icon field in *LandingHero → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_hero.items[].icon
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	icon: prismic.ImageField<never>;
	
	/**
	 * keyword field in *LandingHero → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_hero.items[].keyword
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	keyword: prismic.RichTextField;
}

/**
 * Default variation for LandingHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: LandingHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingHeroSliceDefault = prismic.SharedSliceVariation<"default", Simplify<LandingHeroSliceDefaultPrimary>, Simplify<LandingHeroSliceDefaultItem>>;

/**
 * Slice variation for *LandingHero*
 */
type LandingHeroSliceVariation = LandingHeroSliceDefault

/**
 * LandingHero Shared Slice
 *
 * - **API ID**: `landing_hero`
 * - **Description**: LandingHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingHeroSlice = prismic.SharedSlice<"landing_hero", LandingHeroSliceVariation>;

/**
 * Primary content in *LandingProjects → Default → Primary*
 */
export interface OurProjectsSliceDefaultPrimary {
	/**
	 * Title field in *LandingProjects → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: This is where it all begins...
	 * - **API ID Path**: our_projects.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * Description field in *LandingProjects → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: A nice description of your feature
	 * - **API ID Path**: our_projects.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
	
	/**
	 * ctaText field in *LandingProjects → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: our_projects.default.primary.ctatext
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	ctatext: prismic.RichTextField;
	
	/**
	 * ctaUrl field in *LandingProjects → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: our_projects.default.primary.ctaurl
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	ctaurl: prismic.LinkField;
}

/**
 * Primary content in *LandingProjects → Items*
 */
export interface OurProjectsSliceDefaultItem {
	/**
	 * projectTitle field in *LandingProjects → Items*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: our_projects.items[].projecttitle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	projecttitle: prismic.TitleField;
	
	/**
	 * location field in *LandingProjects → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: our_projects.items[].location
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	location: prismic.RichTextField;
	
	/**
	 * projectDescription field in *LandingProjects → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: our_projects.items[].projectdescription
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	projectdescription: prismic.RichTextField;
	
	/**
	 * before field in *LandingProjects → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: our_projects.items[].before
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	before: prismic.ImageField<never>;
	
	/**
	 * after field in *LandingProjects → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: our_projects.items[].after
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	after: prismic.ImageField<never>;
}

/**
 * Default variation for LandingProjects Slice
 *
 * - **API ID**: `default`
 * - **Description**: OurProjects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurProjectsSliceDefault = prismic.SharedSliceVariation<"default", Simplify<OurProjectsSliceDefaultPrimary>, Simplify<OurProjectsSliceDefaultItem>>;

/**
 * Slice variation for *LandingProjects*
 */
type OurProjectsSliceVariation = OurProjectsSliceDefault

/**
 * LandingProjects Shared Slice
 *
 * - **API ID**: `our_projects`
 * - **Description**: OurProjects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurProjectsSlice = prismic.SharedSlice<"our_projects", OurProjectsSliceVariation>;

/**
 * Primary content in *LandingServices → Default → Primary*
 */
export interface LandingServicesSliceDefaultPrimary {
	/**
	 * title field in *LandingServices → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_services.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
}

/**
 * Primary content in *LandingServices → Items*
 */
export interface LandingServicesSliceDefaultItem {
	/**
	 * bgimage field in *LandingServices → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_services.items[].bgimage
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	bgimage: prismic.ImageField<never>;
	
	/**
	 * servicetitle field in *LandingServices → Items*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_services.items[].servicetitle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	servicetitle: prismic.TitleField;
	
	/**
	 * description field in *LandingServices → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_services.items[].description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
	
	/**
	 * link field in *LandingServices → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_services.items[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Default variation for LandingServices Slice
 *
 * - **API ID**: `default`
 * - **Description**: LandingServices
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingServicesSliceDefault = prismic.SharedSliceVariation<"default", Simplify<LandingServicesSliceDefaultPrimary>, Simplify<LandingServicesSliceDefaultItem>>;

/**
 * Primary content in *LandingServices → nohover → Primary*
 */
export interface LandingServicesSliceNohoverPrimary {
	/**
	 * title field in *LandingServices → nohover → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_services.nohover.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * ctaText field in *LandingServices → nohover → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_services.nohover.primary.ctatext
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	ctatext: prismic.RichTextField;
	
	/**
	 * ctaUrl field in *LandingServices → nohover → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_services.nohover.primary.ctaurl
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	ctaurl: prismic.LinkField;
}

/**
 * Primary content in *LandingServices → Items*
 */
export interface LandingServicesSliceNohoverItem {
	/**
	 * bgimage field in *LandingServices → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_services.items[].bgimage
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	bgimage: prismic.ImageField<never>;
	
	/**
	 * servicetitle field in *LandingServices → Items*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_services.items[].servicetitle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	servicetitle: prismic.TitleField;
	
	/**
	 * description field in *LandingServices → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_services.items[].description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
}

/**
 * nohover variation for LandingServices Slice
 *
 * - **API ID**: `nohover`
 * - **Description**: LandingServices
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingServicesSliceNohover = prismic.SharedSliceVariation<"nohover", Simplify<LandingServicesSliceNohoverPrimary>, Simplify<LandingServicesSliceNohoverItem>>;

/**
 * Slice variation for *LandingServices*
 */
type LandingServicesSliceVariation = LandingServicesSliceDefault | LandingServicesSliceNohover

/**
 * LandingServices Shared Slice
 *
 * - **API ID**: `landing_services`
 * - **Description**: LandingServices
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingServicesSlice = prismic.SharedSlice<"landing_services", LandingServicesSliceVariation>;

/**
 * Primary content in *LandingSubhero → Items*
 */
export interface LandingSubheroSliceDefaultItem {
	/**
	 * text field in *LandingSubhero → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_subhero.items[].text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;
}

/**
 * Default variation for LandingSubhero Slice
 *
 * - **API ID**: `default`
 * - **Description**: LandingSubhero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingSubheroSliceDefault = prismic.SharedSliceVariation<"default", Record<string, never>, Simplify<LandingSubheroSliceDefaultItem>>;

/**
 * Slice variation for *LandingSubhero*
 */
type LandingSubheroSliceVariation = LandingSubheroSliceDefault

/**
 * LandingSubhero Shared Slice
 *
 * - **API ID**: `landing_subhero`
 * - **Description**: LandingSubhero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingSubheroSlice = prismic.SharedSlice<"landing_subhero", LandingSubheroSliceVariation>;

/**
 * Primary content in *LandingTimeline → Default → Primary*
 */
export interface LandingTimelineSliceDefaultPrimary {
	/**
	 * Title field in *LandingTimeline → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: This is where it all begins...
	 * - **API ID Path**: landing_timeline.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
}

/**
 * Primary content in *LandingTimeline → Items*
 */
export interface LandingTimelineSliceDefaultItem {
	/**
	 * title field in *LandingTimeline → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_timeline.items[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;
	
	/**
	 * step field in *LandingTimeline → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_timeline.items[].step
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	step: prismic.RichTextField;
}

/**
 * Default variation for LandingTimeline Slice
 *
 * - **API ID**: `default`
 * - **Description**: LandingTimeline
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingTimelineSliceDefault = prismic.SharedSliceVariation<"default", Simplify<LandingTimelineSliceDefaultPrimary>, Simplify<LandingTimelineSliceDefaultItem>>;

/**
 * Slice variation for *LandingTimeline*
 */
type LandingTimelineSliceVariation = LandingTimelineSliceDefault

/**
 * LandingTimeline Shared Slice
 *
 * - **API ID**: `landing_timeline`
 * - **Description**: LandingTimeline
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingTimelineSlice = prismic.SharedSlice<"landing_timeline", LandingTimelineSliceVariation>;

/**
 * Primary content in *LandingVideoShowcase → Default → Primary*
 */
export interface LandingVideoShowcaseSliceDefaultPrimary {
	/**
	 * Title field in *LandingVideoShowcase → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: This is where it all begins...
	 * - **API ID Path**: landing_video_showcase.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * Description field in *LandingVideoShowcase → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: A nice description of your feature
	 * - **API ID Path**: landing_video_showcase.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
}

/**
 * Primary content in *LandingVideoShowcase → Items*
 */
export interface LandingVideoShowcaseSliceDefaultItem {
	/**
	 * video field in *LandingVideoShowcase → Items*
	 *
	 * - **Field Type**: Link to Media
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_video_showcase.items[].video
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	video: prismic.LinkToMediaField;
}

/**
 * Default variation for LandingVideoShowcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: LandingVideoShowcase
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingVideoShowcaseSliceDefault = prismic.SharedSliceVariation<"default", Simplify<LandingVideoShowcaseSliceDefaultPrimary>, Simplify<LandingVideoShowcaseSliceDefaultItem>>;

/**
 * Primary content in *LandingVideoShowcase → backgroundColor → Primary*
 */
export interface LandingVideoShowcaseSliceBackgroundColorPrimary {
	/**
	 * Title field in *LandingVideoShowcase → backgroundColor → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: This is where it all begins...
	 * - **API ID Path**: landing_video_showcase.backgroundColor.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * Description field in *LandingVideoShowcase → backgroundColor → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: A nice description of your feature
	 * - **API ID Path**: landing_video_showcase.backgroundColor.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
}

/**
 * Primary content in *LandingVideoShowcase → Items*
 */
export interface LandingVideoShowcaseSliceBackgroundColorItem {
	/**
	 * video field in *LandingVideoShowcase → Items*
	 *
	 * - **Field Type**: Link to Media
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_video_showcase.items[].video
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	video: prismic.LinkToMediaField;
}

/**
 * backgroundColor variation for LandingVideoShowcase Slice
 *
 * - **API ID**: `backgroundColor`
 * - **Description**: LandingVideoShowcase
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingVideoShowcaseSliceBackgroundColor = prismic.SharedSliceVariation<"backgroundColor", Simplify<LandingVideoShowcaseSliceBackgroundColorPrimary>, Simplify<LandingVideoShowcaseSliceBackgroundColorItem>>;

/**
 * Slice variation for *LandingVideoShowcase*
 */
type LandingVideoShowcaseSliceVariation = LandingVideoShowcaseSliceDefault | LandingVideoShowcaseSliceBackgroundColor

/**
 * LandingVideoShowcase Shared Slice
 *
 * - **API ID**: `landing_video_showcase`
 * - **Description**: LandingVideoShowcase
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingVideoShowcaseSlice = prismic.SharedSlice<"landing_video_showcase", LandingVideoShowcaseSliceVariation>;

/**
 * Primary content in *LogoList → Default → Primary*
 */
export interface LogoListSliceDefaultPrimary {
	/**
	 * title field in *LogoList → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo_list.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * description field in *LogoList → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo_list.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
}

/**
 * Primary content in *LogoList → Items*
 */
export interface LogoListSliceDefaultItem {
	/**
	 * logoImage field in *LogoList → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo_list.items[].logoImage
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	logoImage: prismic.ImageField<never>;
}

/**
 * Default variation for LogoList Slice
 *
 * - **API ID**: `default`
 * - **Description**: LogoList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoListSliceDefault = prismic.SharedSliceVariation<"default", Simplify<LogoListSliceDefaultPrimary>, Simplify<LogoListSliceDefaultItem>>;

/**
 * Primary content in *LogoList → Items*
 */
export interface LogoListSliceOnlyLogosBgItem {
	/**
	 * logoImage field in *LogoList → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo_list.items[].logoImage
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	logoImage: prismic.ImageField<never>;
}

/**
 * onlyLogosBg variation for LogoList Slice
 *
 * - **API ID**: `onlyLogosBg`
 * - **Description**: LogoList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoListSliceOnlyLogosBg = prismic.SharedSliceVariation<"onlyLogosBg", Record<string, never>, Simplify<LogoListSliceOnlyLogosBgItem>>;

/**
 * Primary content in *LogoList → buttonTitleDescription → Primary*
 */
export interface LogoListSliceButtonTitleDescriptionPrimary {
	/**
	 * title field in *LogoList → buttonTitleDescription → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo_list.buttonTitleDescription.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;
}

/**
 * Primary content in *LogoList → Items*
 */
export interface LogoListSliceButtonTitleDescriptionItem {
	/**
	 * logoImage field in *LogoList → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo_list.items[].logoImage
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	logoImage: prismic.ImageField<never>;
	
	/**
	 * subtitle field in *LogoList → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Titulo ...
	 * - **API ID Path**: logo_list.items[].subtitle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subtitle: prismic.RichTextField;
	
	/**
	 * description field in *LogoList → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Descripción ...
	 * - **API ID Path**: logo_list.items[].description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;
	
	/**
	 * buttonlink field in *LogoList → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo_list.items[].buttonlink
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	buttonlink: prismic.LinkField;
	
	/**
	 * buttontext field in *LogoList → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo_list.items[].buttontext
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	buttontext: prismic.KeyTextField;
}

/**
 * buttonTitleDescription variation for LogoList Slice
 *
 * - **API ID**: `buttonTitleDescription`
 * - **Description**: LogoList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoListSliceButtonTitleDescription = prismic.SharedSliceVariation<"buttonTitleDescription", Simplify<LogoListSliceButtonTitleDescriptionPrimary>, Simplify<LogoListSliceButtonTitleDescriptionItem>>;

/**
 * Slice variation for *LogoList*
 */
type LogoListSliceVariation = LogoListSliceDefault | LogoListSliceOnlyLogosBg | LogoListSliceButtonTitleDescription

/**
 * LogoList Shared Slice
 *
 * - **API ID**: `logo_list`
 * - **Description**: LogoList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoListSlice = prismic.SharedSlice<"logo_list", LogoListSliceVariation>;

/**
 * Primary content in *Metrics → Default → Primary*
 */
export interface MetricsSliceDefaultPrimary {
	/**
	 * title field in *Metrics → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: metrics.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
}

/**
 * Primary content in *Metrics → Items*
 */
export interface MetricsSliceDefaultItem {
	/**
	 * contentText field in *Metrics → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: metrics.items[].contenttext
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	contenttext: prismic.KeyTextField;
	
	/**
	 * subtitle field in *Metrics → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: metrics.items[].subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField;
}

/**
 * Default variation for Metrics Slice
 *
 * - **API ID**: `default`
 * - **Description**: Metrics
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MetricsSliceDefault = prismic.SharedSliceVariation<"default", Simplify<MetricsSliceDefaultPrimary>, Simplify<MetricsSliceDefaultItem>>;

/**
 * Primary content in *Metrics → noBackground → Primary*
 */
export interface MetricsSliceNoBackgroundPrimary {
	/**
	 * title field in *Metrics → noBackground → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: metrics.noBackground.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
}

/**
 * Primary content in *Metrics → Items*
 */
export interface MetricsSliceNoBackgroundItem {
	/**
	 * contentText field in *Metrics → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: metrics.items[].contenttext
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	contenttext: prismic.KeyTextField;
	
	/**
	 * subtitle field in *Metrics → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: metrics.items[].subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField;
}

/**
 * noBackground variation for Metrics Slice
 *
 * - **API ID**: `noBackground`
 * - **Description**: Metrics
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MetricsSliceNoBackground = prismic.SharedSliceVariation<"noBackground", Simplify<MetricsSliceNoBackgroundPrimary>, Simplify<MetricsSliceNoBackgroundItem>>;

/**
 * Slice variation for *Metrics*
 */
type MetricsSliceVariation = MetricsSliceDefault | MetricsSliceNoBackground

/**
 * Metrics Shared Slice
 *
 * - **API ID**: `metrics`
 * - **Description**: Metrics
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MetricsSlice = prismic.SharedSlice<"metrics", MetricsSliceVariation>;

/**
 * Primary content in *Projects → Default → Primary*
 */
export interface ProjectsSliceDefaultPrimary {
	/**
	 * imgSwapp field in *Projects → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.default.primary.imgswapp
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	imgswapp: prismic.ImageField<never>;
	
	/**
	 * subtitle field in *Projects → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField;
	
	/**
	 * description field in *Projects → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
	
	/**
	 * title field in *Projects → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
}

/**
 * Default variation for Projects Slice
 *
 * - **API ID**: `default`
 * - **Description**: Projects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ProjectsSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Projects*
 */
type ProjectsSliceVariation = ProjectsSliceDefault

/**
 * Projects Shared Slice
 *
 * - **API ID**: `projects`
 * - **Description**: Projects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsSlice = prismic.SharedSlice<"projects", ProjectsSliceVariation>;

/**
 * Primary content in *Services → Default → Primary*
 */
export interface ServicesSliceDefaultPrimary {
	/**
	 * title field in *Services → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * description field in *Services → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
	
	/**
	 * image field in *Services → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * buttontext field in *Services → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.default.primary.buttontext
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	buttontext: prismic.KeyTextField;
}

/**
 * Primary content in *Services → Items*
 */
export interface ServicesSliceDefaultItem {
	/**
	 * imageList field in *Services → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.items[].imagelist
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	imagelist: prismic.ImageField<never>;
	
	/**
	 * titleList field in *Services → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.items[].titlelist
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	titlelist: prismic.KeyTextField;
	
	/**
	 * descriptionList field in *Services → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.items[].descriptionlist
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	descriptionlist: prismic.KeyTextField;
}

/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ServicesSliceDefaultPrimary>, Simplify<ServicesSliceDefaultItem>>;

/**
 * Primary content in *Services → noIconsNoButtons → Primary*
 */
export interface ServicesSliceNoIconsNoButtonsPrimary {
	/**
	 * title field in *Services → noIconsNoButtons → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.noIconsNoButtons.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * description field in *Services → noIconsNoButtons → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.noIconsNoButtons.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
	
	/**
	 * image field in *Services → noIconsNoButtons → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.noIconsNoButtons.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * noIconsNoButtons variation for Services Slice
 *
 * - **API ID**: `noIconsNoButtons`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceNoIconsNoButtons = prismic.SharedSliceVariation<"noIconsNoButtons", Simplify<ServicesSliceNoIconsNoButtonsPrimary>, never>;

/**
 * Primary content in *Services → noIcons → Primary*
 */
export interface ServicesSliceNoIconsPrimary {
	/**
	 * title field in *Services → noIcons → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.noIcons.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * description field in *Services → noIcons → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.noIcons.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
	
	/**
	 * image field in *Services → noIcons → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.noIcons.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * buttontext field in *Services → noIcons → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.noIcons.primary.buttontext
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	buttontext: prismic.KeyTextField;
}

/**
 * noIcons variation for Services Slice
 *
 * - **API ID**: `noIcons`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceNoIcons = prismic.SharedSliceVariation<"noIcons", Simplify<ServicesSliceNoIconsPrimary>, never>;

/**
 * Primary content in *Services → imageText → Primary*
 */
export interface ServicesSliceImageTextPrimary {
	/**
	 * title field in *Services → imageText → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.imageText.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * image field in *Services → imageText → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.imageText.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * imageText variation for Services Slice
 *
 * - **API ID**: `imageText`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceImageText = prismic.SharedSliceVariation<"imageText", Simplify<ServicesSliceImageTextPrimary>, never>;

/**
 * Slice variation for *Services*
 */
type ServicesSliceVariation = ServicesSliceDefault | ServicesSliceNoIconsNoButtons | ServicesSliceNoIcons | ServicesSliceImageText

/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSlice = prismic.SharedSlice<"services", ServicesSliceVariation>;

/**
 * Primary content in *Staff → Default → Primary*
 */
export interface StaffSliceDefaultPrimary {
	/**
	 * title field in *Staff → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: staff.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;
}

/**
 * Primary content in *Staff → Items*
 */
export interface StaffSliceDefaultItem {
	/**
	 * image field in *Staff → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: staff.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * nametitle field in *Staff → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: staff.items[].nametitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	nametitle: prismic.KeyTextField;
	
	/**
	 * positiontitle field in *Staff → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: staff.items[].positiontitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	positiontitle: prismic.KeyTextField;
	
	/**
	 * linkedinlogo field in *Staff → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: staff.items[].linkedinlogo
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	linkedinlogo: prismic.ImageField<never>;
	
	/**
	 * profileurl field in *Staff → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: staff.items[].profileurl
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	profileurl: prismic.LinkField;
}

/**
 * Default variation for Staff Slice
 *
 * - **API ID**: `default`
 * - **Description**: Staff
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StaffSliceDefault = prismic.SharedSliceVariation<"default", Simplify<StaffSliceDefaultPrimary>, Simplify<StaffSliceDefaultItem>>;

/**
 * Slice variation for *Staff*
 */
type StaffSliceVariation = StaffSliceDefault

/**
 * Staff Shared Slice
 *
 * - **API ID**: `staff`
 * - **Description**: Staff
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StaffSlice = prismic.SharedSlice<"staff", StaffSliceVariation>;

declare module "@prismicio/client" {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismicClient.ClientConfig): prismicClient.Client<AllDocumentTypes>;
	}
	
	namespace Content {
		export type {
			FootermenuDocument,
			FootermenuDocumentData,
			FootermenuDocumentDataLinkgroupItem,
			FootermenuDocumentDataSocialmediagroupItem,
			HomepageDocument,
			HomepageDocumentData,
			HomepageDocumentDataSlicesSlice,
			LandingfooterDocument,
			LandingfooterDocumentData,
			LandingfooterDocumentDataContactgroupItem,
			LandingfooterDocumentDataNavlinksItem,
			LandingnavDocument,
			LandingnavDocumentData,
			LandingnavDocumentDataNavlinkItem,
			LandingpageDocument,
			LandingpageDocumentData,
			LandingpageDocumentDataSlicesSlice,
			MenutopDocument,
			MenutopDocumentData,
			MenutopDocumentDataMenulinksItem,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			AllDocumentTypes,
			CardListSlice,
			CardListSliceDefaultPrimary,
			CardListSliceDefaultItem,
			CardListSliceVariation,
			CardListSliceDefault,
			ClientsSlice,
			ClientsSliceDefaultPrimary,
			ClientsSliceDefaultItem,
			ClientsSliceVariation,
			ClientsSliceDefault,
			ContactSlice,
			ContactSliceDefaultPrimary,
			ContactSliceCotizarFormPrimary,
			ContactSliceVariation,
			ContactSliceDefault,
			ContactSliceCotizarForm,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceNoButtonNoDescriptionPrimary,
			HeroSliceNoButtonPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			HeroSliceNoButtonNoDescription,
			HeroSliceNoButton,
			IdeasSlice,
			IdeasSliceDefaultPrimary,
			IdeasSliceNoButtonNobgPrimary,
			IdeasSliceNoButtonPrimary,
			IdeasSliceVariation,
			IdeasSliceDefault,
			IdeasSliceNoButtonNobg,
			IdeasSliceNoButton,
			AboutSlice,
			AboutSliceDefaultPrimary,
			AboutSliceVariation,
			AboutSliceDefault,
			SliceBenefitsSlice,
			SliceBenefitsSliceDefaultPrimary,
			SliceBenefitsSliceDefaultItem,
			SliceBenefitsSliceVariation,
			SliceBenefitsSliceDefault,
			LandingBenefitsTopSlice,
			LandingBenefitsTopSliceDefaultPrimary,
			LandingBenefitsTopSliceDefaultItem,
			LandingBenefitsTopSliceVariation,
			LandingBenefitsTopSliceDefault,
			LandingClosingFormSlice,
			LandingClosingFormSliceDefaultPrimary,
			LandingClosingFormSliceVariation,
			LandingClosingFormSliceDefault,
			LandingCustomerReviewSlice,
			LandingCustomerReviewSliceDefaultPrimary,
			LandingCustomerReviewSliceDefaultItem,
			LandingCustomerReviewSliceVariation,
			LandingCustomerReviewSliceDefault,
			LandingFaqSlice,
			LandingFaqSliceDefaultPrimary,
			LandingFaqSliceDefaultItem,
			LandingFaqSliceVariation,
			LandingFaqSliceDefault,
			LandingHeroSlice,
			LandingHeroSliceDefaultPrimary,
			LandingHeroSliceDefaultItem,
			LandingHeroSliceVariation,
			LandingHeroSliceDefault,
			OurProjectsSlice,
			OurProjectsSliceDefaultPrimary,
			OurProjectsSliceDefaultItem,
			OurProjectsSliceVariation,
			OurProjectsSliceDefault,
			LandingServicesSlice,
			LandingServicesSliceDefaultPrimary,
			LandingServicesSliceDefaultItem,
			LandingServicesSliceNohoverPrimary,
			LandingServicesSliceNohoverItem,
			LandingServicesSliceVariation,
			LandingServicesSliceDefault,
			LandingServicesSliceNohover,
			LandingSubheroSlice,
			LandingSubheroSliceDefaultItem,
			LandingSubheroSliceVariation,
			LandingSubheroSliceDefault,
			LandingTimelineSlice,
			LandingTimelineSliceDefaultPrimary,
			LandingTimelineSliceDefaultItem,
			LandingTimelineSliceVariation,
			LandingTimelineSliceDefault,
			LandingVideoShowcaseSlice,
			LandingVideoShowcaseSliceDefaultPrimary,
			LandingVideoShowcaseSliceDefaultItem,
			LandingVideoShowcaseSliceBackgroundColorPrimary,
			LandingVideoShowcaseSliceBackgroundColorItem,
			LandingVideoShowcaseSliceVariation,
			LandingVideoShowcaseSliceDefault,
			LandingVideoShowcaseSliceBackgroundColor,
			LogoListSlice,
			LogoListSliceDefaultPrimary,
			LogoListSliceDefaultItem,
			LogoListSliceOnlyLogosBgItem,
			LogoListSliceButtonTitleDescriptionPrimary,
			LogoListSliceButtonTitleDescriptionItem,
			LogoListSliceVariation,
			LogoListSliceDefault,
			LogoListSliceOnlyLogosBg,
			LogoListSliceButtonTitleDescription,
			MetricsSlice,
			MetricsSliceDefaultPrimary,
			MetricsSliceDefaultItem,
			MetricsSliceNoBackgroundPrimary,
			MetricsSliceNoBackgroundItem,
			MetricsSliceVariation,
			MetricsSliceDefault,
			MetricsSliceNoBackground,
			ProjectsSlice,
			ProjectsSliceDefaultPrimary,
			ProjectsSliceVariation,
			ProjectsSliceDefault,
			ServicesSlice,
			ServicesSliceDefaultPrimary,
			ServicesSliceDefaultItem,
			ServicesSliceNoIconsNoButtonsPrimary,
			ServicesSliceNoIconsPrimary,
			ServicesSliceImageTextPrimary,
			ServicesSliceVariation,
			ServicesSliceDefault,
			ServicesSliceNoIconsNoButtons,
			ServicesSliceNoIcons,
			ServicesSliceImageText,
			StaffSlice,
			StaffSliceDefaultPrimary,
			StaffSliceDefaultItem,
			StaffSliceVariation,
			StaffSliceDefault
		}
	}
}