// Code generated by Slice Machine. DO NOT EDIT.

import CardList from './CardList';
import Comparative from './Comparative';
import Contact from './Contact';
import Hero from './Hero';
import Ideas from './Ideas';
import LandingFaq from './LandingFaq';
import LandingHero from './LandingHero';
import LandingTimeline from './LandingTimeline';
import LogoList from './LogoList';
import Metrics from './Metrics';
import Projects from './Projects';
import Services from './Services';
import Staff from './Staff';

export {
	CardList,
	Comparative,
	Contact,
	Hero,
	Ideas,
	LandingFaq,
	LandingHero,
	LandingTimeline,
	LogoList,
	Metrics,
	Projects,
	Services,
	Staff,
};

export const components = {
	card_list: CardList,
	clients: Comparative,
	contact: Contact,
	hero: Hero,
	ideas: Ideas,
	landing_faq: LandingFaq,
	landing_hero: LandingHero,
	landing_timeline: LandingTimeline,
	logo_list: LogoList,
	metrics: Metrics,
	projects: Projects,
	services: Services,
	staff: Staff,
};
