// Code generated by Slice Machine. DO NOT EDIT.

import About from './About';
import CardList from './CardList';
import Comparative from './Comparative';
import Contact from './Contact';
import Hero from './Hero';
import Ideas from './Ideas';
import LandingCustomerReview from './LandingCustomerReview';
import LandingFaq from './LandingFaq';
import LandingHero from './LandingHero';
import LandingServices from './LandingServices';
import LandingTimeline from './LandingTimeline';
import LogoList from './LogoList';
import Metrics from './Metrics';
import OurProjects from './OurProjects';
import Projects from './Projects';
import Services from './Services';
import Staff from './Staff';

export {
	About,
	CardList,
	Comparative,
	Contact,
	Hero,
	Ideas,
	LandingCustomerReview,
	LandingFaq,
	LandingHero,
	LandingServices,
	LandingTimeline,
	LogoList,
	Metrics,
	OurProjects,
	Projects,
	Services,
	Staff,
};

export const components = {
	about: About,
	card_list: CardList,
	clients: Comparative,
	contact: Contact,
	hero: Hero,
	ideas: Ideas,
	landing_customer_review: LandingCustomerReview,
	landing_faq: LandingFaq,
	landing_hero: LandingHero,
	landing_services: LandingServices,
	landing_timeline: LandingTimeline,
	logo_list: LogoList,
	metrics: Metrics,
	our_projects: OurProjects,
	projects: Projects,
	services: Services,
	staff: Staff,
};
